### ISSUE TITLE
Paving the way to 0.4.17

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/Gradus.jl#159]
It's been a few weeks since the last release, and much has changed in the main branch. This issue is to track what still needs to be done before 0.4.17 release:

- [ ] Documentation examples need to be updated and recomputed 
- [ ] #154 needs to be documented
- [ ] #150 needs to be documented
- [ ] #148 needs to be documented (debug toolkit)
- [ ] #157 needs to be documented
- [ ] #141 needs to be documented

**Comment by fjebaker** [comment]
Considering we are including breaking changes, we should release this as 0.5.0.
